"""empty message

Revision ID: 383fee01e712
Revises: ed4b5cb03198
Create Date: 2022-07-16 07:16:00.597966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383fee01e712'
down_revision = 'ed4b5cb03198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'rent', type_='foreignkey')
    # op.drop_constraint(None, 'rent', type_='foreignkey')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rent', 'users', ['end_at'], ['id'])
    op.create_foreign_key(None, 'rent', 'users', ['start_at'], ['id'])
    # ### end Alembic commands ###
