"""empty message

Revision ID: 98e77b35cf26
Revises: 84a13ecd9d75
Create Date: 2022-07-15 15:58:22.005791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e77b35cf26'
down_revision = '84a13ecd9d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_issued', sa.String(), nullable=True))
    op.add_column('users', sa.Column('issue_date', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_series', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_num', sa.String(), nullable=True))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthplace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthplace')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'passport_num')
    op.drop_column('users', 'passport_series')
    op.drop_column('users', 'department_code')
    op.drop_column('users', 'issue_date')
    op.drop_column('users', 'passport_issued')
    # ### end Alembic commands ###
