"""empty message

Revision ID: c6b51a7de90f
Revises: 0c72f47ef06c
Create Date: 2022-07-16 11:44:34.185512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b51a7de90f'
down_revision = '0c72f47ef06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passport_photo')
    # ### end Alembic commands ###
